---
name: Static Analysis
on: [push, pull_request]
jobs:
  Markdown_Lint_Check:
    name: Markdown Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run markdownlint
        run: |
          echo "Checking Markdown files"
          find . -type f -name "*.md" -print0 | xargs -0 markdownlint
